port: "8080"
addres: "localhost:8080"

dbPostgres:
  username: "postgres"
  host: "postgres"
  port: "5432"
  dbname: "MEDODS"
  sslmode: "disable"
  password : "260203"

signingKey : "asd[i31l]asd98_LKd1das"

